arr1=(persuing B.Tech)
arr[0]="Devansh"
arr[1]="Kumar"
arr[2]="Shukla"
arr[3]="From"
arr[4]="GLA"
arr[5]="University"
echo "First Element : ${arr[0]} "
echo "Second Element : ${arr[1]} "
echo "Third Element : ${arr[2]} "
echo "Fourth Element : ${arr[3]} "
echo "Fifth Element : ${arr[4]} "
echo "Sixth Element : ${arr[5]} "
echo "All Elements : ${arr[*]} "
echo "All Element : ${arr[@]} "
echo "All Element From Index 0 to 3 : ${arr[*]:0:3} "
echo "All Element from index 3 : ${arr[@]:3} "
echo "Length of arr array : ${#arr[@]} "
echo "Length of element at index 0 of arr array : ${#arr[0]} "
echo -n "
"
echo "All Elements of arr1 : ${arr1[@]} "
echo "Length of arr1 array : ${#arr1[@]} "
echo -n "
"
echo "Enter the elemetnts in new array : "
read -a arr2
echo -n "
"
echo "All Elements of array arr2: ${arr2[@]} "
echo "Length of arr2 array : ${#arr2[@]} "
